# Generated by Django 4.2.26 on 2025-12-03 02:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clock_in_time', models.DateTimeField(blank=True, null=True)),
                ('clock_out_time', models.DateTimeField(blank=True, null=True)),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('break_duration', models.DecimalField(decimal_places=2, default=0, help_text='Break duration in hours', max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('PARTIAL', 'Partial Day'), ('OVERTIME', 'Overtime'), ('HALF_DAY', 'Half Day'), ('EARLY_OUT', 'Early Out')], default='ABSENT', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_overtime', models.BooleanField(default=False)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee')),
            ],
            options={
                'ordering': ['-date', '-clock_in_time'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_work_hours', models.DecimalField(decimal_places=2, default=8.0, help_text='Standard work hours per day', max_digits=4)),
                ('late_threshold_minutes', models.IntegerField(default=15, help_text='Minutes after which arrival is considered late')),
                ('overtime_threshold_hours', models.DecimalField(decimal_places=2, default=8.0, help_text='Hours after which overtime starts', max_digits=4)),
                ('standard_start_time', models.TimeField(default='09:00:00', help_text='Standard work start time')),
                ('standard_end_time', models.TimeField(default='17:00:00', help_text='Standard work end time')),
                ('allow_early_clock_in_minutes', models.IntegerField(default=30, help_text='Minutes before standard time employees can clock in')),
                ('max_break_duration_hours', models.DecimalField(decimal_places=2, default=1.0, help_text='Maximum break duration per day in hours', max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Settings',
                'verbose_name_plural': 'Attendance Settings',
            },
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['employee', 'date'], name='attendance__employe_b6a945_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['date'], name='attendance__date_337b1d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['status'], name='attendance__status_741eb8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('employee', 'date')},
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('attendance.attendancerecord',),
        ),
    ]
